### ISSUE TITLE
Can't open perl script "src/utils/eval.pl": No such file or directory

### ISSUE THREAD

**Issue by binnd** [elikip/htparser#1]
Hi,
This error occurred while I was training model.
I wonder if you could provided eval.pl file.

Many thanks

**Comment by elikip** [comment]
Have you looked in the GitHub repository?

Eli.

**Comment by elikip** [comment]
Sorry, I must have forgotten to upload the file.
The file can be found at https://github.com/elikip/bist-parser/blob/master/bmstparser/src/utils/eval.pl
